[workspace]
members = [
    "programs/gateway",
    "programs/realm-voter",
    "programs/nft-voter",
    "programs/token-haver",
    "programs/core-voter",
]

[profile.release]
overflow-checks = true